### ISSUE TITLE
Individual Post Page - EJS

### ISSUE THREAD

**Issue by wolfmcr** [wil-gerard/world-pizza#21]

**Comment by wil-gerard** [comment]
It would be nice if users could see the title, caption, and likes here

for Pizza = likes, I noticed Leon uses a Node package called methodOverride to use forms for put. ?_method comes from methodOverride

<form
  class="col-1"
  action="/post/likePost/<%= post.id %>?_method=PUT"
  method="POST"
>

also.... Pizza emoji HTML unicode = &#127829
